### ISSUE TITLE
how to get this

### ISSUE THREAD

**Issue by ProntoHiran** [tom-walford/sbt-snyk#2]
From where can I download this plugin

ypesafe repository: unable to get resource for org/tom/walford#sbt-snyk;0.1: res=http://repo.typesafe.com/typesafe/releases/org/tom/wal,.....

**Comment by tom-walford** [comment]
It's on the sonatype repository (maven central)

`resolvers +=  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"`
